### ISSUE TITLE
Error when requesting invoice

### ISSUE THREAD

**Issue by TripKey** [ElementsProject/filebazaar#3]
Hello,

I am getting the following error when clicking to pay for the image and requesting an invoice. I had everything working but now this happens.

POST /_invoice 500 47.941 ms - 148
Error: write EPROTO 139995458078528:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

    at _errnoException (util.js:1003:13)
    at WriteWrap.afterWrite [as oncomplete] (net.js:863:14)
GET /IMG_4349.jpg?preview 200 5.690 ms - 5214134

**Comment by shesek** [comment]
What URL did you configure for `--charge-url` when starting filebazaar?

**Comment by TripKey** [comment]
Default

charge_url: https://localhost:9112

**Comment by shesek** [comment]
Try `http://localhost:9112/`, not `https://`

**Comment by shesek** [comment]
Or just don't set `charge_url` at all, `http://localhost:9112/` is the default value you get if nothing is set.

**Comment by TripKey** [comment]
That was it, thanks very much.
