### ISSUE TITLE
NaN token, no download possible.

### ISSUE THREAD

**Issue by kiwiidb** [ElementsProject/filebazaar#4]
Everything works fine but when I pay the invoice, the page redirects to the preview page. The token variable in the URL contains "NaN": 
`
GET /_invoice/JNW52x79Wir5KIuZPE4qJ/longpoll.png 200 11409.545 ms - 68
GET /duck.jpg?invoice=JNW52x79Wir5KIuZPE4qJ 302 5.038 ms - 212
GET /duck.jpg?token=JNW52x79Wir5KIuZPE4qJ.NaN.svWchyqGCyv5PnMZXwJ0mDUF9JRKwswsHdCxcJlkcP8 200 149.135 ms - 1937
GET /_themes/yeti/bootstrap.min.css 304 0.607 ms - -
GET /_assets/style.css 304 0.390 ms - -
GET /duck.jpg?preview 304 1.009 ms - -
`

**Comment by shesek** [comment]
That was due to a change in lightning-charge that wasn't reflected here. Fixed in c8fdf19ed600dc1b1769b9d0cbcc13bf66c2342a, released in `v0.2.5`.

Thanks for the bug report!
