### ISSUE TITLE
Getting EACCESS and ELIFECYCLE errors trying to install on Ubuntu 18.04

### ISSUE THREAD

**Issue by chrisguida** [ElementsProject/filebazaar#6]
See https://github.com/Automattic/node-canvas/issues/788#issuecomment-532392523

**Comment by shesek** [comment]
Thanks for the report. I updated to node-canvas v2 and published filebazaar v0.2.7. Can you check if this fixes the issue?

**Comment by chrisguida** [comment]
Still got the issue, although i think it may have been a permission issue on my end, I'm not sure.

I made myself owner of some npm-related folders, for instance:

`sudo chown -R `whoami` /usr/local/lib/node_modules`

...and that seems to have fixed the issue.

**Comment by chrisguida** [comment]
Well, I tried `npm install filebazaar@0.2.6` and now I'm having permission issues again :(

**Comment by chrisguida** [comment]
Okay, weird, next I tried

`sudo npm install -g filebazaar`

Which gave me the symlink permission issue *and* the ELIFECYCLE error again.

Tried `npm install -g filebazaar` again, just to see what the error was, and boom! No error.

I'm so confused.

**Comment by chrisguida** [comment]
Oh, I think I know what happened. I `sudo rm`'d the symlink, so now it doesn't need permission to overwrite the old symlink I think.

**Comment by chrisguida** [comment]
Okay never mind. I see what's happening.

I run `npm install -g filebazaar@0.2.6` and it gives me a "can't create symlink" EACCESS error.

Then I run `sudo npm install -g filebazaar@0.2.6` and I get an ELIFECYCLE error, but the symlink gets created. It doesn't appear to be pointing to anything, though, which makes it appear red in `ls -al`.

Then I run `npm install -g filebazaar@0.2.6` once again, and I get the ELIFECYCLE error.

Then I run `npm install -g filebazaar` to install 0.2.7, and the installation completes successfully.

So, yes, your update fixed the problem, but I also have some weird symlink creation problems. Is it best practice to `chown` `/usr/local/bin` to a non-root user?

**Comment by shesek** [comment]
What I would recommend is configuring npm to install global packages inside your home directory. See [instructions here](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally#manually-change-npms-default-directory). This typically resolves these pesky npm permission issues, which can indeed be a pain with how npm ships by default :(
